// Generated by the Maven Archetype Plug-in
package net.formiguinhas.app;

import org.apache.log4j.Logger;

import net.formiguinhas.negocios.Usuario;
import er.extensions.appserver.ERXSession;
import er.extensions.foundation.ERXProperties;
import er.extensions.localization.ERXLocalizer;

public class Session extends ERXSession {

	private static final Logger log = Logger.getLogger(Session.class);


	private static final long serialVersionUID = 1L;

	private Usuario usuario;

	private String theme;

	private NavigationController navController;

	public Session() {
		super();
		setLanguage(ERXLocalizer.defaultLanguage());
		return;
	}

	
	public Usuario usuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTheme() {
		return ERXProperties.stringForKey("app.css.login.path");
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	// MODERNLOOK

	public NavigationController navController() {
		if (navController == null) {
			navController = new NavigationController(this);
		}
		return navController;
	}
}
